import { Heart, ShieldCheck, Sparkles, Users } from "lucide-react";
import CTA from "../../components/CTA";

export default function About() {
  return <>
    <section className="page-hero"><div className="container page-hero-grid"><div><div className="eyebrow">About PetCard</div><h1>Making pet care feel <span>more organized.</span></h1><p>PetCard is being built to give pet parents a simple place to organize important information about their pets and stay on top of everyday care.</p></div><div className="pet-visual"><div className="pet-orb"/><div className="pet-card"><div className="screen-top"><span>PetCard</span><span>♥</span></div><div className="pet-avatar">🐱</div><h3>Our Mission</h3><div className="breed">Simple · Helpful · Pet-first</div><div className="mini-row"><span>Care</span><b>✓</b></div><div className="mini-row"><span>Organization</span><b>✓</b></div><div className="mini-row"><span>Peace of mind</span><b>✓</b></div></div></div></div></section>
    <section className="section"><div className="container"><div className="stats"><div className="stat"><strong>Pet</strong><span>Focused experience</span></div><div className="stat"><strong>Simple</strong><span>Designed for everyday use</span></div><div className="stat"><strong>One</strong><span>Organized place</span></div><div className="stat"><strong>Care</strong><span>At the center of the product</span></div></div></div></section>
    <section className="section soft"><div className="container center"><div className="eyebrow">What We Believe</div><h2 className="section-title">Built around <span>pet parents.</span></h2><p className="section-subtitle">Until official company copy is finalized, this section intentionally uses broad brand messaging rather than invented founder or company claims.</p><div className="feature-grid"><div className="feature-card"><div className="feature-icon"><Heart/></div><h3>Love for Pets</h3><p>Every feature starts with making pet care a little easier.</p></div><div className="feature-card"><div className="feature-icon"><ShieldCheck/></div><h3>Trust & Privacy</h3><p>We aim to treat pet and user information responsibly.</p></div><div className="feature-card"><div className="feature-icon"><Sparkles/></div><h3>Simplicity</h3><p>Clear experiences without unnecessary complexity.</p></div><div className="feature-card"><div className="feature-icon"><Users/></div><h3>Pet Parents First</h3><p>Designed around real everyday pet-care needs.</p></div></div></div></section>
    <CTA title="A simpler way to care for your pet." text="PetCard is being built with everyday pet parents in mind."/>
  </>;
}
